version: "3.9"
services:
  server:
    image: sinal/server:latest
    environment:
      CORS_ORIGIN: "https://sinal.ovoleur.dev"
    ports:
      - "4000:4000"
  client:
    image: sinal/client:latest
    environment:
      NEXT_PUBLIC_SERVER_HTTP_URL: "http://sinal.ovoleur.dev/api"
      NEXT_PUBLIC_SERVER_WS_URL: "ws://sinal.ovoleur.dev"
      NEXT_PUBLIC_SERVER_WS_PATH: "/api/socket.io"
    ports:
      - "3000:3000"
