version: "3.9"
services:
  server:
    image: sinal/server:latest
    build: ./server
    environment:
      CORS_ORIGIN: "http://localhost:3000"
    ports:
      - "4000:4000"
  client:
    image: sinal/client:latest
    build: ./client
    ports:
      - "3000:3000"
