version: "3.9"
services:
  server:
    image: sinal/server:latest
    environment:
      CORS_ORIGIN: "https://sinal.ovoleur.dev"
    ports:
      - "4000:4000"
  client:
    image: sinal/client:latest
    ports:
      - "3000:3000"
